# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codenerix_invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codenerix_products', '0001_initial'),
        ('codenerix_pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbasket',
            name='pos_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_sales', to='codenerix_pos.POSSlot', verbose_name='Point of Sales'),
        ),
        migrations.AddField(
            model_name='salesalbaran',
            name='billing_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albaran_sales', to='codenerix_invoicing.BillingSeries', verbose_name='Billing series'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineticketrectification',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_ticket_rectification', to='codenerix_invoicing.SalesLineTicketRectification', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineticketrectification',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_ticket_rectification', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineticketrectification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_ticket_rectification', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineticket',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_ticket', to='codenerix_invoicing.SalesLineTicket', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineticket',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_ticket', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_ticket', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineorder',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_order', to='codenerix_invoicing.SalesLineOrder', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineorder',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_order', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_order', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineinvoicerectification',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_invoice_rectification', to='codenerix_invoicing.SalesLineInvoiceRectification', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineinvoicerectification',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_invoice_rectification', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineinvoicerectification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_invoice_rectification', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineinvoice',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_invoice', to='codenerix_invoicing.SalesLineInvoice', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineinvoice',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_invoice', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlineinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_invoice', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlinebasket',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_basket', to='codenerix_invoicing.SalesLineBasket', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlinebasket',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_basket', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlinebasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_basket', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlinealbaran',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_albaran', to='codenerix_invoicing.SalesLineAlbaran', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlinealbaran',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_albaran', to='codenerix_invoicing.ReasonModification', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='reasonmodificationlinealbaran',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_line_albaran', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='purchasesticketrectificationdocument',
            name='ticket_rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketrectificationdocument_purchases', to='codenerix_invoicing.PurchasesTicketRectification', verbose_name='Ticket rectification'),
        ),
        migrations.AddField(
            model_name='purchasesticketdocument',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketdocument_purchases', to='codenerix_invoicing.PurchasesTicket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='purchasesticket',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to='codenerix_invoicing.Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='purchasesorderdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdocument_purchases', to='codenerix_invoicing.PurchasesOrder', verbose_name='Purchases order'),
        ),
        migrations.AddField(
            model_name='purchasesorder',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_purchases', to='codenerix_invoicing.PurchasesBudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='purchasesorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_purchases', to='codenerix_invoicing.Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='purchaseslineticketrectification',
            name='line_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ticketrectification_purchases', to='codenerix_invoicing.PurchasesLineTicket', verbose_name='Line ticket'),
        ),
        migrations.AddField(
            model_name='purchaseslineticketrectification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ticketrectification_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseslineticketrectification',
            name='ticket_rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ticketrectification_purchases', to='codenerix_invoicing.PurchasesTicketRectification', verbose_name='Ticket rectification'),
        ),
        migrations.AddField(
            model_name='purchaseslineticket',
            name='line_albaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_ticket_purchases', to='codenerix_invoicing.PurchasesLineAlbaran', verbose_name='Line albaran'),
        ),
        migrations.AddField(
            model_name='purchaseslineticket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_ticket_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseslineticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ticket_purchases', to='codenerix_invoicing.PurchasesTicket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='purchaseslineorder',
            name='line_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_order_purchases', to='codenerix_invoicing.PurchasesLineBudget', verbose_name='Line budget'),
        ),
        migrations.AddField(
            model_name='purchaseslineorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_order_purchases', to='codenerix_invoicing.PurchasesOrder', verbose_name='Purchase order'),
        ),
        migrations.AddField(
            model_name='purchaseslineorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_order_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseslineinvoicerectification',
            name='invoice_rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_invoicerectification_purchases', to='codenerix_invoicing.PurchasesInvoiceRectification', verbose_name='Invoice rectification'),
        ),
        migrations.AddField(
            model_name='purchaseslineinvoicerectification',
            name='line_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_invoicerectification_purchases', to='codenerix_invoicing.PurchasesLineInvoice', verbose_name='Line invoice'),
        ),
        migrations.AddField(
            model_name='purchaseslineinvoicerectification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_invoicerectification_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseslineinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_invoice_purchases', to='codenerix_invoicing.PurchasesInvoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='purchaseslineinvoice',
            name='line_albaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_invoice_purchases', to='codenerix_invoicing.PurchasesLineAlbaran', verbose_name='Line albaran'),
        ),
        migrations.AddField(
            model_name='purchaseslineinvoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_invoice_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseslinebudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_budget_purchases', to='codenerix_invoicing.PurchasesBudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='purchaseslinebudget',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_budget_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseslinealbaran',
            name='albaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_albaran_purchases', to='codenerix_invoicing.PurchasesAlbaran', verbose_name='Albaran'),
        ),
        migrations.AddField(
            model_name='purchaseslinealbaran',
            name='line_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_albaran_purchases', to='codenerix_invoicing.PurchasesLineOrder', verbose_name='Line orders'),
        ),
        migrations.AddField(
            model_name='purchaseslinealbaran',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_albaran_purchases', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchasesinvoicerectificationdocument',
            name='invoice_rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicerectificationdocument_purchases', to='codenerix_invoicing.PurchasesInvoiceRectification', verbose_name='Invoice rectification'),
        ),
        migrations.AddField(
            model_name='purchasesinvoicedocument',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicedocument_purchases', to='codenerix_invoicing.PurchasesInvoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='purchasesinvoice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_purchases', to='codenerix_invoicing.Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='purchasesbudgetdocument',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetdocument_purchases', to='codenerix_invoicing.PurchasesBudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='purchasesbudget',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_purchases', to='codenerix_invoicing.Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='purchasesalbarandocument',
            name='albaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarandocument_purchases', to='codenerix_invoicing.PurchasesAlbaran', verbose_name='Albaran'),
        ),
        migrations.AddField(
            model_name='purchasesalbaran',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albaran_purchases', to='codenerix_invoicing.Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='billing_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='codenerix_invoicing.BillingSeries', verbose_name='Billing series'),
        ),
        migrations.AddField(
            model_name='provider',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='providercategories', to='codenerix_products.Category'),
        ),
        migrations.AddField(
            model_name='provider',
            name='type_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='codenerix_products.TypeTax', verbose_name='Type tax'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentticketrectification',
            name='ticket_rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_ticket_rectification', to='codenerix_invoicing.SalesTicketRectification', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentticketrectification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_ticket_rectification', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_ticket', to='codenerix_invoicing.SalesTicket', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_ticket', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_order', to='codenerix_invoicing.SalesOrder', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_order', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentinvoicerectification',
            name='invoice_rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_invoice_rectification', to='codenerix_invoicing.SalesInvoiceRectification', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentinvoicerectification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_invoice_rectification', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_invoice', to='codenerix_invoicing.SalesInvoice', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_invoice', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentbasket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_basket', to='codenerix_invoicing.SalesBasket', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentbasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_basket', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentalbaran',
            name='albaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_albaran', to='codenerix_invoicing.SalesAlbaran', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentalbaran',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_counter_document_albaran', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='codenerix_invoicing.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='codenerix_invoicing.TypeDocument', verbose_name='Type document'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_series', to='codenerix_invoicing.BillingSeries', verbose_name='Billing series'),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='codenerix_products.TypeTax', verbose_name='Type tax'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cash_diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='codenerix_invoicing.CashDiary', verbose_name='Cash diary'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='order',
            field=models.ManyToManyField(related_name='cash_movements', to='codenerix_invoicing.SalesOrder', verbose_name='Sales orders'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='pos_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='codenerix_pos.POSSlot', verbose_name='Slot'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cashdiary',
            name='closed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_cash_diarys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cashdiary',
            name='opened_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_cash_diarys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cashdiary',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='codenerix_pos.POS', verbose_name='Point of Sales'),
        ),
        migrations.AlterUniqueTogether(
            name='salesticketrectification',
            unique_together=set([('code', 'parent_pk')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesticket',
            unique_together=set([('code', 'parent_pk')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together=set([('code', 'parent_pk')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoicerectification',
            unique_together=set([('code', 'parent_pk')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together=set([('code', 'parent_pk')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesbasket',
            unique_together=set([('code', 'parent_pk')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesalbaran',
            unique_together=set([('code', 'parent_pk')]),
        ),
    ]
