# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0002_auto_20180117_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='storage',
        ),
    ]
