# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0002_auto_20180118_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslinealbaran',
            name='invoiced',
            field=models.BooleanField(default=False, verbose_name='Invoiced'),
        ),
    ]
