# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0004_auto_20170308_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbudget',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_sales', to='codenerix_invoicing.SalesShoppingCart', verbose_name='Shopping cart'),
        ),
    ]
