# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0011_auto_20180202_0826'),
        ('codenerix_invoicing', '0015_remove_purchaseslinealbaran_product_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseslinealbaran',
            name='product_unique',
            field=models.ManyToManyField(related_name='line_albaran_purchases', to='codenerix_products.ProductUnique', verbose_name='Product Unique'),
        ),
    ]
