# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0017_cashdiary_cashmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesalbaran',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Send'),
        ),
    ]
