# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0018_auto_20170515_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='address_delivery',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='address_invoice',
        ),
        migrations.AddField(
            model_name='salesbasket',
            name='address_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='order_sales_delivery', to='codenerix_invoicing.Address', verbose_name='Address delivery'),
        ),
        migrations.AddField(
            model_name='salesbasket',
            name='address_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='order_sales_invoice', to='codenerix_invoicing.Address', verbose_name='Address invoice'),
        ),
    ]
