# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0030_remove_salesticket_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesalbaran',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesalbaran',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesalbaran',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesalbaran',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='salesbasket',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesbasket',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesbasket',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesbasket',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='salesinvoicerectification',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesinvoicerectification',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesinvoicerectification',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesinvoicerectification',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslinealbaran',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslinealbaran',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslinealbaran',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslinealbaran',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslinebasket',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslinebasket',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslinebasket',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslinebasket',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslineinvoice',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslineinvoice',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslineinvoice',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslineinvoice',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslineinvoicerectification',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslineinvoicerectification',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslineinvoicerectification',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslineinvoicerectification',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslineorder',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslineorder',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslineorder',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslineorder',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslineticket',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslineticket',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslineticket',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslineticket',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleslineticketrectification',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='saleslineticketrectification',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saleslineticketrectification',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='saleslineticketrectification',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='salesticket',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesticket',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesticket',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesticket',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='salesticketrectification',
            name='discounts',
            field=models.FloatField(default=0, editable=False, verbose_name='Discounts'),
        ),
        migrations.AddField(
            model_name='salesticketrectification',
            name='subtotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesticketrectification',
            name='taxes',
            field=models.FloatField(default=0, editable=False, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='salesticketrectification',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
    ]
