# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0039_printcounterdocumentalbaran_printcounterdocumentbasket_printcounterdocumentinvoice_printcounterdocum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printcounterdocumentalbaran',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='printcounterdocumentbasket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='printcounterdocumentinvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='printcounterdocumentinvoicerectification',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='printcounterdocumentorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='printcounterdocumentticket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='printcounterdocumentticketrectification',
            name='quantity',
        ),
        migrations.AddField(
            model_name='printcounterdocumentalbaran',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentbasket',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentinvoice',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentinvoicerectification',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentorder',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentticket',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
        migrations.AddField(
            model_name='printcounterdocumentticketrectification',
            name='status_document',
            field=models.CharField(choices=[('TM', 'Temporary'), ('DF', 'Definitive')], default='TM', max_length=2, verbose_name='Status document'),
        ),
    ]
