# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0049_auto_20170919_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdiary',
            name='closed_cards_extra',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Closed Cards Deviation'),
        ),
        migrations.AddField(
            model_name='cashdiary',
            name='closed_cash_extra',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Closed Cash Deviation'),
        ),
    ]
