# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0052_auto_20170919_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdiary',
            name='closed_cards_notes',
            field=models.TextField(blank=True, default='', verbose_name='Closed Cards Notes'),
        ),
        migrations.AlterField(
            model_name='cashdiary',
            name='closed_cash_notes',
            field=models.TextField(blank=True, default='', verbose_name='Closed Cash Notes'),
        ),
        migrations.AlterField(
            model_name='cashdiary',
            name='opened_cards_notes',
            field=models.TextField(blank=True, default='', verbose_name='Opened Cards Notes'),
        ),
        migrations.AlterField(
            model_name='cashdiary',
            name='opened_cash_notes',
            field=models.TextField(blank=True, default='', verbose_name='Opened Cash Notes'),
        ),
    ]
