# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0058_auto_20171122_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseslineorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_order_purchases', to='codenerix_invoicing.PurchasesOrder', verbose_name='Purchase order'),
        ),
    ]
