# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0061_salesorderdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslinebasket',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='saleslineinvoice',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='saleslineorder',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='saleslineticket',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Code'),
        ),
    ]
