# Generated by Django 2.0.6 on 2018-09-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0063_auto_20171128_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status_order',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Payment accepted'), ('SE', 'Sent'), ('DE', 'Delivered'), ('CA', 'Cancelled')], default='PE', max_length=2, verbose_name='Status'),
        ),
    ]
